# Advertisement service
# Manage advertisements for users
version: v0.1.0
name: advertisement
adapters:
  # Get advertisement
  - steps:
      - adapter:
          repository:
            name: marketing-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
