# Cart service
# Cart for users
version: v0.0.4
name: cart
ingressAdapters:
# Edit cart
- stateless:
    action: write
    variant: rest
    route: update
  steps:
  - egressAdapter:
      stateful:
        name: cart-db
        variant: mongo
        action: write
        size: small
  - egressAdapter:
      stateless:
        variant: rest
        service: recommendation
        action: write
        route: update
  - egressAdapter:
      stateless:
        variant: rest
        service: user-preference
        action: write
        route: update
  - egressAdapter:
      stateless:
        variant: rest
        service: inventory
        action: write
        route: update

# get cart content
- stateless:
    action: read
    variant: rest
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: cart-db
        variant: mongo
        action: read
        size: small
