# Category service
# Manage product Categories
version: v0.1.0
name: category
adapters:
  # Get Categories
  - steps:
      - adapter:
          repository:
            name: content-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
