# Localization service
# Manage User localization
version: v0.1.0
name: localization
adapters:
  # Get User localization
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: update
  # Update User localization
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
