# Notification service
# Manages notifications
version: v0.1.0
name: notification
adapters:
  # Sign up
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: signup
  # Log in
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: login
  # Log out
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: logout
  # Order create
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: ordercreate
  # Order cancel
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: ordercancel
  # Order rescheduled 
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: orderrescheduled
  # Order returned 
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      action: write
      variant: rest
      route: return
deployment: {}
