# Order service
version: v0.1.0
name: order
adapters:
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: cart
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: cost-calculation
            action: write
            route: calculate
      - adapter:
          invocation:
            variant: rest
            service: payment
            action: write
            route: pay
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: write
            route: update
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          invocation:
            variant: rest
            service: notification
            action: write
            route: ordercreate
    server:
      variant: rest
      action: write
      route: checkout
  # Browse order
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: read
            size: medium
      - adapter:
          invocation:
            variant: rest
            service: tracking
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: scheduling
            action: read
            route: get
    server:
      variant: rest
      action: read
      route: get
  # Cancel order
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: read
            size: medium
      - adapter:
          invocation:
            variant: rest
            service: tracking
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: scheduling
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: payment
            action: write
            route: refund
      - adapter:
          invocation:
            variant: rest
            service: notification
            action: write
            route: ordercancel
    server:
      variant: rest
      action: write
      route: cancel
  # order reschedule delivery
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          invocation:
            variant: rest
            service: tracking
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: scheduling
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: notification
            action: write
            route: orderrescheduled
    server:
      variant: rest
      action: write
      route: reschedule
deployment: {}
