# paymet service
version: v0.1.0
name: payment
adapters:
  - steps:
      - adapter:
          repository:
            name: payment-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: pay
  # refund
  - steps:
      - adapter:
          repository:
            name: payment-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: refund
deployment: {}
