# Profile service
# Manage User profie
version: v0.1.0
name: profile
adapters:
  # Get User profile
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: read
            size: medium
    server:
      variant: rest
      action: read
      route: get
  # create User profile
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: medium
    server:
      variant: rest
      action: write
      route: create
  # update User profile
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: medium
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: write
            route: update
    server:
      variant: rest
      action: write
      route: update
deployment: {}
