# Profile service
# Manage User profie
version: v0.0.4
name: profile
ingressAdapters:
# Get User profile
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: read
        size: medium

# create User profile
- stateless:
    variant: rest
    action: write
    route: create
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: medium

# update User profile
- stateless:
    variant: rest
    action: write
    route: update
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: medium
  - egressAdapter:
      stateless:
        variant: rest
        service: user-preference
        action: write
        route: update
