# Recommendation service
# Manage recommendations for users
version: v0.1.0
name: recommendation
adapters:
  # Get recommendations
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
  # Update recommendations
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: write
      route: update
deployment: {}
