# Return service
version: v0.1.0
name: return-order
adapters:
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: cost-calculation
            action: write
            route: return
      - adapter:
          invocation:
            variant: rest
            service: payment
            action: write
            route: pay
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          invocation:
            variant: rest
            service: notification
            action: write
            route: return
    server:
      variant: rest
      action: write
      route: return
deployment: {}
