# Review service
# Manage product reviews
version: v0.1.0
name: review
adapters:
  # Get reviews for product
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: medium
    server:
      variant: rest
      action: read
      route: get
  # write reviews for product
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: write
            route: update
      - adapter:
          invocation:
            variant: rest
            service: recommendation
            action: write
            route: update
    server:
      variant: rest
      action: write
      route: post
deployment: {}
