# order Tracking service
version: v0.0.4
name: tracking
ingressAdapters:
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: shipping-db
        variant: mongo
        action: read
        size: small

