# order Tracking service
version: v0.1.0
name: tracking
adapters:
  - steps:
      - adapter:
          repository:
            name: shipping-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
