# User Preference service
# Manage User preference
version: v0.0.4
name: user-preference
ingressAdapters:
# Get User preference
- stateless:
    variant: rest
    action: write
    route: update
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: read
        size: small

