# User Preference service
# Manage User preference
version: v0.1.0
name: user-preference
adapters:
  # Get User preference
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: update
  # Update User preference
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
