---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rca: ignore
  creationTimestamp: null
  name: user-db
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-db
    spec:
      containers:
      - image: hiroki11hanada/stateful-unit-mongo:v0.0.4
        name: user-db
        ports:
        - containerPort: 27017
          name: mongo
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
      volumes:
      - configMap:
          items:
          - key: env
            path: .env
          name: user-db-env
        name: env
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: user-db
  namespace: the-bench
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 0
  selector:
    app: user-db
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  env: |-
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
    MONGO_INITDB_DATABASE: mongo
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: user-db-env
  namespace: the-bench

