# Auth service
# Authentication and authorization for users
version: v0.1.0
name: auth
adapters:
  # Sign up
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: signup
    server:
      action: write
      variant: rest
      route: signup
  # Log in
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: small
      - adapter:
          invocation:
            variant: rest
            service: profile
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: localization
            action: read
            route: get
      - adapter:
          producer:
            variant: kafka
            topic: login
    server:
      action: write
      variant: rest
      route: login
  # Log out
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: logout
    server:
      action: write
      variant: rest
      route: logout
  # Authenticate
  - steps:
      - adapter:
          repository:
            name: user-db
            variant: mongo
            action: read
            size: small
    server:
      action: read
      variant: rest
      route: authenticate
deployment: {}
