# Cart service
# Cart for users
version: v0.1.0
name: cart
adapters:
  # Edit cart
  - steps:
      - adapter:
          repository:
            name: cart-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: cartedited
    server:
      action: write
      variant: rest
      route: update
  # get cart content
  - steps:
      - adapter:
          repository:
            name: cart-db
            variant: mongo
            action: read
            size: small
    server:
      action: read
      variant: rest
      route: get
deployment: {}
