# Cart service
# Cart for users
version: v0.0.5
name: cart
ingressAdapters:
# Edit cart
- stateless:
    action: write
    variant: rest
    route: update
  steps:
  - egressAdapter:
      stateful:
        name: cart-db
        variant: mongo
        action: write
        size: small
  - egressAdapter:
      broker:
        variant: kafka
        topic: cartedited

# get cart content
- stateless:
    action: read
    variant: rest
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: cart-db
        variant: mongo
        action: read
        size: small
