# Customer support service
version: v0.1.0
name: customer-support
adapters:
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    server:
      variant: rest
      action: write
      route: inquire
deployment: {}
