# Customer support service
version: v0.0.5
name: customer-support
ingressAdapters:
- stateless:
    variant: rest
    action: write
    route: inquire
  steps:
  - egressAdapter:
      stateful:
        name: customer-db
        variant: mongo
        action: write
        size: small
