# Discount service
# Manage product dicounts
version: v0.0.5
name: discount
ingressAdapters:
# Get discounts
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: marketing-db
        variant: mongo
        action: read
        size: small

