# Discount service
# Manage product dicounts
version: v0.1.0
name: discount
adapters:
  # Get discounts
  - steps:
      - adapter:
          repository:
            name: marketing-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
