# Inventory service
# Manage product Inventory
version: v0.0.5
name: inventory
ingressAdapters:
# Get Inventories
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: content-db
        variant: mongo
        action: read
        size: medium

# Update Inventories after cart edit
- broker:
    variant: kafka
    topic: cartedited
  steps:
  - egressAdapter:
      stateful:
        name: content-db
        variant: mongo
        action: write
        size: small

