# Inventory service
# Manage product Inventory
version: v0.1.0
name: inventory
adapters:
  # Get Inventories
  - steps:
      - adapter:
          repository:
            name: content-db
            variant: mongo
            action: read
            size: medium
    server:
      variant: rest
      action: read
      route: get
  # Update Inventories after cart edit
  - steps:
      - adapter:
          repository:
            name: content-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: cartedited
deployment: {}
