# Localization service
# Manage User localization
version: v0.0.5
name: localization
ingressAdapters:
# Update User localization after signup
- broker:
    variant: kafka
    topic: signup
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Get User localization
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: read
        size: small

