# Notification service
# Manages notifications
version: v0.1.0
name: notification
adapters:
  # Sign up
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: signup
  # Log in
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: login
  # Log out
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: logout
  # Order create
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: ordercreated
  # Order cancel
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: ordercancelled
  # Order rescheduled 
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: orderrescheduled
  # Order returned 
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: returnrequested
deployment: {}
