# Order service
version: v0.1.0
name: order
adapters:
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: cart
            action: read
            route: get
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: ordercreated
    server:
      variant: rest
      action: write
      route: checkout
  # Browse order
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: read
            size: medium
      - adapter:
          invocation:
            variant: rest
            service: tracking
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: scheduling
            action: read
            route: get
    server:
      variant: rest
      action: read
      route: get
  # Cancel order
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: read
            size: medium
      - adapter:
          producer:
            variant: kafka
            topic: ordercancelled
    server:
      variant: rest
      action: write
      route: cancel
  # order reschedule delivery
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: tracking
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: scheduling
            action: read
            route: get
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: orderrescheduled
    server:
      variant: rest
      action: write
      route: reschedule
deployment: {}
