# paymet service
version: v0.1.0
name: payment
adapters:
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: cost-calculation
            action: write
            route: calculate
      - adapter:
          repository:
            name: payment-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: ordercreated
  # refund after cancel
  - steps:
      - adapter:
          repository:
            name: payment-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: ordercancelled
  # return
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: cost-calculation
            action: write
            route: return
      - adapter:
          repository:
            name: payment-db
            variant: mongo
            action: write
            size: small
    consumer:
      variant: kafka
      topic: returnrequested
deployment: {}
