# Product Information service
# Manage products
version: v0.1.0
name: product
adapters:
  # Get Many products
  - steps:
      - adapter:
          repository:
            name: content-db
            variant: mongo
            action: read
            size: large
      - adapter:
          invocation:
            variant: rest
            service: inventory
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: localization
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: discount
            action: read
            route: get
    server:
      variant: rest
      action: read
      route: getmany
  # Get Single products detail
  - steps:
      - adapter:
          repository:
            name: content-db
            variant: mongo
            action: read
            size: small
      - adapter:
          invocation:
            variant: rest
            service: inventory
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: localization
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: discount
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: review
            action: read
            route: get
    server:
      variant: rest
      action: read
      route: get
deployment: {}
