# Recommendation service
# Manage recommendations for users
version: v0.1.0
name: recommendation
adapters:
  # Get recommendations
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
  # Update recommendations after product search
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    consumer:
      variant: kafka
      topic: productsearched
  # Update recommendations after cart edit
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    consumer:
      variant: kafka
      topic: cartedited
  # Update recommendations after wishlist edit
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    consumer:
      variant: kafka
      topic: wishlistedited
  # Update recommendations after review posted
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: small
    consumer:
      variant: kafka
      topic: reviewposted
deployment: {}
