# Return service
version: v0.1.0
name: return-order
adapters:
  - steps:
      - adapter:
          repository:
            name: order-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: returnrequested
    server:
      variant: rest
      action: write
      route: return
deployment: {}
