# Review service
# Manage product reviews
version: v0.1.0
name: review
adapters:
  # Get reviews for product
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: read
            size: medium
    server:
      variant: rest
      action: read
      route: get
  # write reviews for product
  - steps:
      - adapter:
          repository:
            name: customer-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: reviewposted
    server:
      variant: rest
      action: write
      route: post
deployment: {}
