# scheduling service
version: v0.1.0
name: scheduling
adapters:
  - steps:
      - adapter:
          repository:
            name: shipping-db
            variant: mongo
            action: read
            size: medium
    server:
      variant: rest
      action: read
      route: calculate
  # get shipment updates
  - steps:
      - adapter:
          repository:
            name: shipping-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: get
deployment: {}
