# Search service
# Search for products
version: v0.1.0
name: search
adapters:
  # Search
  - steps:
      - adapter:
          invocation:
            variant: rest
            service: category
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: recommendation
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: user-preference
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: advertisement
            action: read
            route: get
      - adapter:
          invocation:
            variant: rest
            service: product
            action: read
            route: getmany
      - adapter:
          producer:
            variant: kafka
            topic: productsearched
    server:
      action: read
      variant: rest
      route: search
deployment: {}
