# shipping service
version: v0.0.5
name: shipping
ingressAdapters:
- stateless:
    variant: rest
    action: read
    route: calculate
  steps:
  - egressAdapter:
      stateful:
        name: shipping-db
        variant: mongo
        action: read
        size: small

