# shipping service
version: v0.1.0
name: shipping
adapters:
  - steps:
      - adapter:
          repository:
            name: shipping-db
            variant: mongo
            action: read
            size: small
    server:
      variant: rest
      action: read
      route: calculate
deployment: {}
