# User Preference service
# Manage User preference
version: v0.0.5
name: user-preference
ingressAdapters:
# Update User preference after order created
- broker:
    variant: kafka
    topic: ordercreated
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference after sign up
- broker:
    variant: kafka
    topic: signup
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference after cart edited
- broker:
    variant: kafka
    topic: cartedited
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference after wishlist edited
- broker:
    variant: kafka
    topic: wishlistedited
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference after review posted
- broker:
    variant: kafka
    topic: reviewposted
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Update User preference
- stateless:
    variant: rest
    action: write
    route: update
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: write
        size: small

# Get User preference
- stateless:
    variant: rest
    action: read
    route: get
  steps:
  - egressAdapter:
      stateful:
        name: user-db
        variant: mongo
        action: read
        size: small

