# Wishlist service
# Wishlist for users
version: v0.1.0
name: wishlist
adapters:
  # Edit wishlist
  - steps:
      - adapter:
          repository:
            name: cart-db
            variant: mongo
            action: write
            size: small
      - adapter:
          producer:
            variant: kafka
            topic: wishlistedited
    server:
      action: write
      variant: rest
      route: update
  # get wishilist content
  - steps:
      - adapter:
          repository:
            name: cart-db
            variant: mongo
            action: read
            size: small
    server:
      action: read
      variant: rest
      route: get
deployment: {}
