version: dev
name: shipping
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: GetQuote
    payload:
      size: 16
  steps: []
- server:
    action: simpleRpc
    variant: grpc
    route: ShipOrder
    payload:
      size: 75
  steps: []
