---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cost-calculation
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-calculation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cost-calculation
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: cost-calculation
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: cost-calculation-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cost-calculation
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: cost-calculation
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Cost Calculation service
    version: v0.0.4
    name: cost-calculation
    ingressAdapters:
    - stateless:
        variant: rest
        action: write
        route: calculate
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: auth
            action: read
            route: authenticate
      - egressAdapter:
          stateless:
            variant: rest
            service: product
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: profile
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: scheduling
            action: read
            route: calculate
      - egressAdapter:
          stateless:
            variant: rest
            service: shipping
            action: read
            route: calculate
      - egressAdapter:
          stateless:
            variant: rest
            service: tax
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: discount
            action: read
            route: get

    # return
    - stateless:
        variant: rest
        action: write
        route: return
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: auth
            action: read
            route: authenticate
      - egressAdapter:
          stateless:
            variant: rest
            service: profile
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: scheduling
            action: read
            route: calculate
      - egressAdapter:
          stateless:
            variant: rest
            service: shipping
            action: read
            route: calculate
      - egressAdapter:
          stateless:
            variant: rest
            service: tax
            action: read
            route: get
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cost-calculation-config
  namespace: the-bench

