---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: inventory
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inventory
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: inventory
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: inventory-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: inventory
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: inventory
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |+
    # Inventory service
    # Manage product Inventory
    version: v0.0.4
    name: inventory
    ingressAdapters:
    # Get Inventories
    - stateless:
        variant: rest
        action: read
        route: get
      steps:
      - egressAdapter:
          stateful:
            name: content-db
            variant: mongo
            action: read
            size: medium

    # Update Inventories
    - stateless:
        variant: rest
        action: write
        route: update
      steps:
      - egressAdapter:
          stateful:
            name: content-db
            variant: mongo
            action: write
            size: small

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: inventory-config
  namespace: the-bench

