---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mobile
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mobile
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: mobile
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: mobile-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mobile
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: mobile
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |+
    ---
    # mobile service
    # Gateway for mobile clients
    version: v0.0.4
    name: mobile
    gateway: # load generator specific
      virtualUsers: 100
      duration: 60
    ingressAdapters:
    # Sign up
    - stateless:
        action: write
        variant: rest
        route: signup
        weight: 1
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: auth
            action: write
            route: signup

    # Log in
    - stateless:
        action: write
        variant: rest
        route: login
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: auth
            action: write
            route: login

    # Log out
    - stateless:
        action: write
        variant: rest
        route: logout
        weight: 5
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: auth
            action: write
            route: logout

    # Search products
    - stateless:
        action: read
        variant: rest
        route: search
        weight: 50
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: search
            action: read
            route: search

    # Search products
    - stateless:
        action: read
        variant: rest
        route: product
        weight: 80
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: product
            action: read
            route: get

    # Edit Cart
    - stateless:
        action: write
        variant: rest
        route: editcart
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: cart
            action: write
            route: update

    # Edit Wishlist
    - stateless:
        action: write
        variant: rest
        route: editwishlist
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: wishlist
            action: write
            route: update

    # Checkout
    - stateless:
        action: write
        variant: rest
        route: checkout
        weight: 8
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: order
            action: write
            route: checkout

    # Browse Cart
    - stateless:
        action: read
        variant: rest
        route: cart
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: cart
            action: read
            route: get

    # Browse wishlist
    - stateless:
        action: read
        variant: rest
        route: wishlist
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: wishlist
            action: read
            route: get

    # update profile
    - stateless:
        action: write
        variant: rest
        route: profile
        weight: 3
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: profile
            action: write
            route: update

    # Browse Order
    - stateless:
        action: write
        variant: rest
        route: browseorder
        weight: 10
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: order
            action: read
            route: get

    # Cancel Order
    - stateless:
        action: write
        variant: rest
        route: cancel
        weight: 1
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: order
            action: write
            route: cancel

    # Reschedule
    - stateless:
        action: write
        variant: rest
        route: reschedule
        weight: 1
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: order
            action: write
            route: reschedule

    # Return
    - stateless:
        action: write
        variant: rest
        route: return
        weight: 1
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: return-order
            action: write
            route: return

    # Review
    - stateless:
        action: write
        variant: rest
        route: review
        weight: 5
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: review
            action: write
            route: post

    # Customer support
    - stateless:
        action: write
        variant: rest
        route: inquire
        weight: 1
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: customer-support
            action: write
            route: inquire

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mobile-config
  namespace: the-bench

