---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: product
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: product
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: product-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: product
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: product
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Product Information service
    # Manage products
    version: v0.0.4
    name: product
    ingressAdapters:
    # Get Many products
    - stateless:
        variant: rest
        action: read
        route: getmany
      steps:
      - egressAdapter:
          stateful:
            name: content-db
            variant: mongo
            action: read
            size: large
      - egressAdapter:
          stateless:
            variant: rest
            service: inventory
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: localization
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: discount
            action: read
            route: get

    # Get Single products detail
    - stateless:
        variant: rest
        action: read
        route: get
      steps:
      - egressAdapter:
          stateful:
            name: content-db
            variant: mongo
            action: read
            size: small
      - egressAdapter:
          stateless:
            variant: rest
            service: inventory
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: localization
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: discount
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: user-preference
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: review
            action: read
            route: get
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: product-config
  namespace: the-bench

