---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: recommendation
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: recommendation
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: recommendation
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: recommendation-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: recommendation
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: recommendation
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Recommendation service
    # Manage recommendations for users
    version: v0.0.4
    name: recommendation
    ingressAdapters:
    # Get recommendations
    - stateless:
        variant: rest
        action: read
        route: get
      steps:
      - egressAdapter:
          stateful:
            name: customer-db
            variant: mongo
            action: read
            size: small

    # Update recommendations
    - stateless:
        variant: rest
        action: write
        route: update
      steps:
      - egressAdapter:
          stateful:
            name: customer-db
            variant: mongo
            action: read
            size: small
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: recommendation-config
  namespace: the-bench

