---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: return-order
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: return-order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: return-order
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: return-order
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: return-order-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: return-order
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: return-order
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |+
    # Return service
    version: v0.0.4
    name: return-order
    ingressAdapters:
    - stateless:
        variant: rest
        action: write
        route: return
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: cost-calculation
            action: write
            route: return
      - egressAdapter:
          stateless:
            variant: rest
            service: payment
            action: write
            route: pay
      - egressAdapter:
          stateful:
            name: order-db
            variant: mongo
            action: write
            size: small
      - egressAdapter:
          stateless:
            variant: rest
            service: notification
            action: write
            route: return

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: return-order-config
  namespace: the-bench

