---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: review
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: review
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: review
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: review-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: review
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: review
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Review service
    # Manage product reviews
    version: v0.0.4
    name: review
    ingressAdapters:
    # Get reviews for product
    - stateless:
        variant: rest
        action: read
        route: get
      steps:
      - egressAdapter:
          stateful:
            name: customer-db
            variant: mongo
            action: read
            size: medium

    # write reviews for product
    - stateless:
        variant: rest
        action: write
        route: post
      steps:
      - egressAdapter:
          stateful:
            name: customer-db
            variant: mongo
            action: write
            size: small
      - egressAdapter:
          stateless:
            variant: rest
            service: user-preference
            action: write
            route: update
      - egressAdapter:
          stateless:
            variant: rest
            service: recommendation
            action: write
            route: update
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: review-config
  namespace: the-bench

