---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: search
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: search
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: search
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: search-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: search
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: search
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Search service
    # Search for products
    version: v0.0.4
    name: search
    ingressAdapters:
    # Search
    - stateless:
        action: read
        variant: rest
        route: search
      steps:
      - egressAdapter:
          stateless:
            variant: rest
            service: category
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: recommendation
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: user-preference
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: advertisement
            action: read
            route: get
      - egressAdapter:
          stateless:
            variant: rest
            service: product
            action: read
            route: getmany
      - egressAdapter:
          stateless:
            variant: rest
            service: recommendation
            action: write
            route: update
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: search-config
  namespace: the-bench

