---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shipping
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shipping
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: shipping
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: shipping-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: shipping
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: shipping
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |+
    # shipping service
    version: v0.0.4
    name: shipping
    ingressAdapters:
    - stateless:
        variant: rest
        action: read
        route: calculate
      steps:
      - egressAdapter:
          stateful:
            name: shipping-db
            variant: mongo
            action: read
            size: small

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: shipping-config
  namespace: the-bench

