---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: template
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: template
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: template
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: template-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: template
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: template
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |+
    # Template service
    version: v0.0.4
    name: template
    ingressAdapters:
    - stateless:
        variant: rest
        action: read
        route: get
      steps: []

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: template-config
  namespace: the-bench

