---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wishlist
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wishlist
    spec:
      containers:
      - image: hiroki11hanada/service-unit:v0.0.4
        name: wishlist
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: wishlist-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: wishlist
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: wishlist
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    # Wishlist service
    # Wishlist for users
    version: v0.0.4
    name: wishlist
    ingressAdapters:
    # Edit wishlist
    - stateless:
        action: write
        variant: rest
        route: update
      steps:
      - egressAdapter:
          stateful:
            name: cart-db
            variant: mongo
            action: write
            size: small
      - egressAdapter:
          stateless:
            variant: rest
            service: recommendation
            action: write
            route: update
      - egressAdapter:
          stateless:
            variant: rest
            service: user-preference
            action: write
            route: update

    # get wishilist content
    - stateless:
        action: read
        variant: rest
        route: get
      steps:
      - egressAdapter:
          stateful:
            name: cart-db
            variant: mongo
            action: read
            size: small
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: wishlist-config
  namespace: the-bench

